package br.inf.portalfiscal.nfe.wsdl.nfeinutilizacao.ba;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NfeInutilizacao", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao", wsdlLocation = "file:/Users/rafael/Desktop/NfeInutilizacao.wsdl")
public class NfeInutilizacao
    extends Service
{

    private final static URL NFEINUTILIZACAO_WSDL_LOCATION;
    private final static WebServiceException NFEINUTILIZACAO_EXCEPTION;
    private final static QName NFEINUTILIZACAO_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao", "NfeInutilizacao");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/rafael/Desktop/NfeInutilizacao.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFEINUTILIZACAO_WSDL_LOCATION = url;
        NFEINUTILIZACAO_EXCEPTION = e;
    }

    public NfeInutilizacao() {
        super(__getWsdlLocation(), NFEINUTILIZACAO_QNAME);
    }

    public NfeInutilizacao(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFEINUTILIZACAO_QNAME, features);
    }

    public NfeInutilizacao(URL wsdlLocation) {
        super(wsdlLocation, NFEINUTILIZACAO_QNAME);
    }

    public NfeInutilizacao(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFEINUTILIZACAO_QNAME, features);
    }

    public NfeInutilizacao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeInutilizacao(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfeInutilizacaoSoap
     */
    @WebEndpoint(name = "NfeInutilizacaoSoap")
    public NfeInutilizacaoSoap getNfeInutilizacaoSoap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao", "NfeInutilizacaoSoap"), NfeInutilizacaoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeInutilizacaoSoap
     */
    @WebEndpoint(name = "NfeInutilizacaoSoap")
    public NfeInutilizacaoSoap getNfeInutilizacaoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao", "NfeInutilizacaoSoap"), NfeInutilizacaoSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns NfeInutilizacaoSoap
     */
    @WebEndpoint(name = "NfeInutilizacaoSoap12")
    public NfeInutilizacaoSoap getNfeInutilizacaoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao", "NfeInutilizacaoSoap12"), NfeInutilizacaoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeInutilizacaoSoap
     */
    @WebEndpoint(name = "NfeInutilizacaoSoap12")
    public NfeInutilizacaoSoap getNfeInutilizacaoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao", "NfeInutilizacaoSoap12"), NfeInutilizacaoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFEINUTILIZACAO_EXCEPTION!= null) {
            throw NFEINUTILIZACAO_EXCEPTION;
        }
        return NFEINUTILIZACAO_WSDL_LOCATION;
    }

}
