package br.inf.portalfiscal.nfe.wsdl.nfeautorizacao3.pr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NfeAutorizacaoSoap12", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NfeAutorizacaoSoap12 {


    /**
     * Transmissao de Lote de NF-e
     * 
     * @param nfeCabecMsg
     * @param nfeDadosMsg
     * @return
     *     returns br.inf.portalfiscal.nfe.wsdl.nfeautorizacao3.NfeAutorizacaoLoteResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3/nfeAutorizacaoLote")
    @WebResult(name = "nfeAutorizacaoLoteResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", partName = "nfeAutorizacaoLoteResult")
    public NfeAutorizacaoLoteResult nfeAutorizacaoLote(
        @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", partName = "nfeDadosMsg")
        NfeDadosMsg nfeDadosMsg,
        @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", header = true, mode = WebParam.Mode.INOUT, partName = "nfeCabecMsg")
        Holder<NfeCabecMsg> nfeCabecMsg);

    /**
     * Transmissao de Lote Compactado de NF-e
     * 
     * @param nfeDadosMsgZip
     * @param nfeCabecMsg
     * @return
     *     returns br.inf.portalfiscal.nfe.wsdl.nfeautorizacao3.NfeAutorizacaoLoteZipResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3/nfeAutorizacaoLoteZip")
    @WebResult(name = "nfeAutorizacaoLoteZipResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", partName = "nfeAutorizacaoLoteZipResult")
    public NfeAutorizacaoLoteZipResult nfeAutorizacaoLoteZip(
        @WebParam(name = "nfeDadosMsgZip", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", partName = "nfeDadosMsgZip")
        NfeDadosMsgZip nfeDadosMsgZip,
        @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", header = true, mode = WebParam.Mode.INOUT, partName = "nfeCabecMsg")
        Holder<NfeCabecMsg> nfeCabecMsg);

}
