package br.inf.portalfiscal.nfe.wsdl.nfeautorizacao3.pr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Servico destinado a recepcao de mensagens de lote de NF-e.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NfeAutorizacao3", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", wsdlLocation = "https://nfe.fazenda.pr.gov.br/nfe/NFeAutorizacao3?wsdl")
@HandlerChain(file="handler-nfeautorizacao.xml")
public class NfeAutorizacao3
    extends Service
{

    private final static URL NFEAUTORIZACAO3_WSDL_LOCATION;
    private final static WebServiceException NFEAUTORIZACAO3_EXCEPTION;
    private final static QName NFEAUTORIZACAO3_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", "NfeAutorizacao3");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://nfe.fazenda.pr.gov.br/nfe/NFeAutorizacao3?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFEAUTORIZACAO3_WSDL_LOCATION = url;
        NFEAUTORIZACAO3_EXCEPTION = e;
    }

    public NfeAutorizacao3() {
        super(__getWsdlLocation(), NFEAUTORIZACAO3_QNAME);
    }

    public NfeAutorizacao3(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFEAUTORIZACAO3_QNAME, features);
    }

    public NfeAutorizacao3(URL wsdlLocation) {
        super(wsdlLocation, NFEAUTORIZACAO3_QNAME);
    }

    public NfeAutorizacao3(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFEAUTORIZACAO3_QNAME, features);
    }

    public NfeAutorizacao3(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeAutorizacao3(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfeAutorizacaoSoap12
     */
    @WebEndpoint(name = "NfeAutorizacaoServicePort")
    public NfeAutorizacaoSoap12 getNfeAutorizacaoServicePort() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", "NfeAutorizacaoServicePort"), NfeAutorizacaoSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeAutorizacaoSoap12
     */
    @WebEndpoint(name = "NfeAutorizacaoServicePort")
    public NfeAutorizacaoSoap12 getNfeAutorizacaoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3", "NfeAutorizacaoServicePort"), NfeAutorizacaoSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFEAUTORIZACAO3_EXCEPTION!= null) {
            throw NFEAUTORIZACAO3_EXCEPTION;
        }
        return NFEAUTORIZACAO3_WSDL_LOCATION;
    }

}
